from colored import fore, back, style
print(fore.BLUE)
print("Program by Trains77")
print()
print("Background Music: https://www.FesliyanStudios.com")
print()
print("Made with Atom Editor")
print()
print("Utilizes Pygame")
print()
print("Other Used Resources: www.javatpoint.com")
print(style.RESET)
